include:
  - project: 'qa-auto/qa-auto-ci'
    file: '.qa-auto.tests.gitlab-ci.yml'

stages:
  - test-dev
  - test-rc
  - test-prod

.run_test_image:
  tags:
    - qa-erm-srm

run_tests:
  extends: .run_test_image
  when: manual
  allow_failure: true

# джобы с названием 'qa_test_...' запускает робот
qa_test_dev_sale:
  extends: run_tests
  stage: test-dev
  when: on_success
  allow_failure: true
  variables:
    ENV: dev
    PRODUCT: 'crm-api.crm'
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    ALLURE_RQL: 'cf["Epic"] in ["[SALE] Crm-Api"] and not tag in ["not_automated","skip_for_dev"]'
    ALLURE_LAUNCH_NAME: 'crm-api.crm_{JIRA_ISSUE}_{ENV}_{CI_JOB_STARTED_AT}'
  needs:
    - deploy-dev
  except:
    - master
    - /^release/
    - schedules

test_rc_sale:
  extends: run_tests
  stage: test-rc
  when: manual
  allow_failure: true
  variables:
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    AUTO_TEST_RUNNER: erm-ssr.rc
  needs:
    - deploy-rc
  except:
    - master
  only:
    - /^release/

test_prod_sale:
  extends: run_tests
  stage: test-prod
  when: manual
  allow_failure: true
  variables:
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    AUTO_TEST_RUNNER: erm-ssr.prod
  needs:
    - deploy-prod
  except:
    refs:
      - schedules
    variables:
      - $IS_WIP_PROJECT == "1"
  only:
    - master
    - /^release/
