include:
  - project: 'qa-auto/qa-auto-ci'
    file: '.qa-auto.tests.gitlab-ci.yml'

stages:
  - test-dev
  - test-rc
  - test-prod

.run_test_image:
  tags:
    - qa-erm-srm

run_tests:
  allow_failure: true

# джобы с названием 'qa_test_...' запускает робот
qa_test_dev_sale:
  extends: run_tests
  stage: test-dev
  when: on_success
  variables:
    ENV: dev
    PRODUCT: 'payments.crm'
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    ALLURE_RQL: 'cf["Epic"] is "[SALE] Payments" and not tag in ["not_automated","skip_for_dev"]'
    ALLURE_LAUNCH_NAME: 'payments.crm_{JIRA_ISSUE}_{ENV}_{CI_JOB_STARTED_AT}'
  needs:
    - deploy-dev-k8s
  except:
    - master
    - /^release/
    - schedules

test_rc_sale_frontend:
  extends: run_tests
  stage: test-rc
  when: manual
  variables:
    ENV: rc
    PRODUCT: 'erm-ssr'
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    AUTO_TEST_RUNNER: erm-ssr.rc
    ALLURE_RQL: 'not cf["Epic"] in ["[SALE] Admin360","[SALE] UI-ERM"] and not tag in ["not_automated","skip_for_rc"]'
    ALLURE_LAUNCH_NAME: 'ERM-SSR_{JIRA_ISSUE}_{ENV}_{CI_JOB_STARTED_AT}'
  needs:
    - deploy-rc-k8s
  except:
    - master
  only:
    - /^release/

test_prod_sale:
  extends: run_tests
  stage: test-prod
  when: manual
  variables:
    ENV: prod
    PRODUCT: 'erm-ssr'
    AUTO_TEST_REPOSITORY: 'qa-auto/qa-auto-sale-team'
    ALLURE_RQL: 'not cf["Epic"] in ["[SALE] Admin360","[SALE] UI-ERM"] and not tag in ["not_automated","skip_for_prod"]'
    ALLURE_LAUNCH_NAME: 'ERM-SSR_{ENV}_{CI_JOB_STARTED_AT}'
  needs:
    - deploy-prod-k8s
  except:
    refs:
      - schedules
    variables:
      - $IS_WIP_PROJECT == "1"
  only:
    - master
    - /^release/