package ru.action_tech.qa.auto.api_models.accesses.license.v1.license_get_parent

import java.util.*

data class LicenseGetParentResponse(
    val accountId: UUID,
    val actionId: UUID,
    val activateOn: String,
    val activatedContactId: UUID,
    val authCode: String,
    val bitrixId: Int,
    val consumptionStatusModifiedOn: String,
    val extensionPartnerId: UUID,
    val extensionSystemUserId: UUID,
    val id: UUID,
    val individualSaleApproval: Boolean,
    val isAutoActivated: Boolean,
    val licenseTypeCode: Int,
    val loginActivated: String,
    val partnerAmount: Double,
    val partnerAmountBase: Double,
    val partnerSubscribeId: UUID,
    val previousAccessId: UUID,
    val priceLevelId: UUID,
    val productId: UUID,
    val productProgram: Int,
    val renewalsNumber: Int,
    val resubNumber: Int,
    val salesContactId: UUID,
    val salesOn: String,
    val salesPartnerId: UUID,
    val salesSubscribeId: UUID,
    val salesSystemUserId: UUID,
    val serviceActivateOn: String,
    val serviceExpiresOn: String,
    val status: Int,
    val supportPartnerId: UUID,
    val supportSystemUserId: UUID,
    val type: Int,
    val userCount: Int,
    val version: Int,
    val versionDate: String,
    val wasActivated: Boolean,
    val whenResub: Int
)