package ru.action_tech.qa.auto.api_models.payments.bank_statements.v1.bankstatement_get_list_by_payment.response

data class BankStatementGetListByPaymentResponse(
    val actionAccountId: ActionAccountId?,
    val author: Author?,
    val bankStatementDate: String?,
    val benefAccount: String?,
    val bicBankCustomer: String?,
    val corrAccountBankCustomer: String?,
    val createdOn: String?,
    val customer: Customer?,
    val customerAccountNt: String?,
    val datedischargebankclient: String?,
    val `file`: File?,
    val id: String?,
    val isDistributed: Boolean?,
    val nameBankCustomer: String?,
    val number: String?,
    val owner: Owner?,
    val payerInn: String?,
    val payerKPP: String?,
    val payerName: String?,
    val payerPaymentAccount: String?,
    val payment: Payment?,
    val paymentAccount: PaymentAccount?,
    val paymentOrderNumber: String?,
    val paymentPeriod: String?,
    val paymentPurpose: String?,
    val priority: Int?,
    val recipientPaymentAccount: String?,
    val stringorderowner: Stringorderowner?,
    val sum: Int?,
    val supposedOrderNumber: String?
)