package ru.action_tech.qa.auto.api_models.shipment.sendings.v1.sendings_get_by_customer_id

data class SendingsGetByCustomerIdResponse(
    val address1: String?,
    val address2: String?,
    val address3: String?,
    val advanceNr: String?,
    val batchId: String?,
    val batchName: String?,
    val batchNr: String?,
    val contact: String?,
    val courierAddress: String?,
    val custContactId: String?,
    val customerId: String,
    val dateBatchClose: String?,
    val deliveryDate: String?,
    val deliveryNonNotesDate: String?,
    val docDate: String?,
    val fullAddress: String?,
    val invoiceNr: String?,
    val packageFormat: String?,
    val packageFormatId: String?,
    val path: String?,
    val product: String?,
    val registeredSendingNr: String?,
    val sendingCategory: String?,
    val sendingDeliveryResultId: Int?,
    val sendingId: String,
    val sendingNr: String?,
    val sendingType: String?,
    val shipping: String?,
    val status: String?,
    val verificationActName: String?
)