package ru.action_tech.qa.auto.api_models.customer.customer.v1.contacts

data class ContactsResponse(
    val accountingType: String?,
    val bitrixId: String?,
    val bonusBalance: Int,
    val bonusLevel: String,
    val canBeLpr: Boolean,
    val isCorpClient: Boolean,
    val connectedSupportA360Status: String?,
    val connectedSupportStatus: String?,
    val connectedSupportUSStatus: String?,
    val contactInfo: List<ContactInfo>?,
    val country: String?,
    val countryId: String?,
    val createTime: String?,
    val customerSegmentType: String?,
    val customerSize: Int?,
    val customerSizeName: String?,
    val customerType: Int,
    val email: String?,
    val factAddress: String?,
    val firstName: String?,
    val id: String,
    val id2PhoneIsSubmitted: Boolean?,
    val id2PhoneNumber: String?,
    val id2Phonenumber: String?,
    val income: Int?,
    val inn: String?,
    val innSecondary: String?,
    val jobTitleId: String?,
    val jobTitleName: String?,
    val kpp: String?,
    val lastName: String,
    val legalAddress: String?,
    val legalFormId: String?,
    val lockStatus: Int?,
    val lpr: Boolean?,
    val middleName: String?,
    val nalogStateId: String?,
    val name: String,
    val parentAccountId: String?,
    val pin: String,
    val region: String?,
    val regionId: String?,
    val scopeAccount: String?,
    val supportStatus: String,
    val supportStatusA360: String?,
    val supportUSStatus: String?,
    val taxation: Int?,
    val timeShift: Int?,
    val flagsUnsubmitted: Boolean
) {
    data class ContactInfo(
        val contactId: String?,
        val contactInfoId: String?,
        val countryCode: String?,
        val countryId: String?,
        val createdOn: String?,
        val recommendedCallTime: Any?,
        val extension: String?,
        val iso: String?,
        val name: String?,
        val sort: Int?,
        val type: Int?,
        val validationStatuses: List<ValidationStatuses>?,
        val comment: String?,
        val isBlocked: Boolean?
    ) {
        data class ValidationStatuses(
            val status: Int?,
            val additionalInfo: String?
        )
    }
}